apiVersion: v1
kind: Service
metadata:
  name: dns-svc-lb-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: kube-dns
spec:
  selector:
    k8s-app: kube-dns
  type:  LoadBalancer
  loadBalancerIP: 172.17.255.10 
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
