kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watch_pods
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watch_pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watch_pods
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  apiGroup: rbac.authorization.k8s.io