apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.3.0
        ports:
        - containerPort: 9113
        args:
          - -nginx.scrape-uri=http://nginx-monitoring.default.svc.cluster.local/basic_status

---
#service targeting nginx-exporter
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: monitoring
  labels:
    app: nginx-exporter
spec:
  ports:
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: nginx-exporter
 
