build_frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n  ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/src/frontend --dockerfile $CI_PROJECT_DIR/src/frontend/Dockerfile --destination $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_TAG 
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/

build_adservice:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n  ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/src/adservice --dockerfile $CI_PROJECT_DIR/src/adservice/Dockerfile --destination $CI_REGISTRY_IMAGE/adservice:$CI_COMMIT_TAG
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/

build_cartservice:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n  ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/src/cartservice --dockerfile $CI_PROJECT_DIR/src/cartservice/Dockerfile --destination $CI_REGISTRY_IMAGE/cartservice:$CI_COMMIT_TAG
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/

build_checkoutservice:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n  ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/src/checkoutservice --dockerfile $CI_PROJECT_DIR/src/checkoutservice/Dockerfile --destination $CI_REGISTRY_IMAGE/checkoutservice:$CI_COMMIT_TAG
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/

build_currencyservice:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n  ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/src/currencyservice --dockerfile $CI_PROJECT_DIR/src/currencyservice/Dockerfile --destination $CI_REGISTRY_IMAGE/currencyservice:$CI_COMMIT_TAG
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/

build_emailservice:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script: 
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n  ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/src/emailservice --dockerfile $CI_PROJECT_DIR/src/emailservice/Dockerfile --destination $CI_REGISTRY_IMAGE/emailservice:$CI_COMMIT_TAG
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/

build_loadgenerator:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n  ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/src/loadgenerator --dockerfile $CI_PROJECT_DIR/src/loadgenerator/Dockerfile --destination $CI_REGISTRY_IMAGE/loadgenerator:$CI_COMMIT_TAG
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/

build_paymentservice:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n  ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/src/paymentservice --dockerfile $CI_PROJECT_DIR/src/paymentservice/Dockerfile --destination $CI_REGISTRY_IMAGE/paymentservice:$CI_COMMIT_TAG
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/

build_productcatalogservice:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n  ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/src/productcatalogservice --dockerfile $CI_PROJECT_DIR/src/productcatalogservice/Dockerfile --destination $CI_REGISTRY_IMAGE/productcatalogservice:$CI_COMMIT_TAG
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/

build_recommendationservice:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n  ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/src/recommendationservice --dockerfile $CI_PROJECT_DIR/src/recommendationservice/Dockerfile --destination $CI_REGISTRY_IMAGE/recommendationservice:$CI_COMMIT_TAG
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/

build_shippingservice:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n  ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/src/shippingservice --dockerfile $CI_PROJECT_DIR/src/shippingservice/Dockerfile --destination $CI_REGISTRY_IMAGE/shippingservice:$CI_COMMIT_TAG
  only:
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG =~ /flux-*/
